version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=open_plant
      - POSTGRES_PASSWORD=plantrulez
    volumes:
      - "/var/lib/postgresql"
      - "/var/lib/postgresql/data"
  